---
- name: "Task: Reboot Servers"
  hosts: all
  become: yes
  become_user: root
  
  tasks:
    - block:
        # --- Discord Messages ---
        - name: "Discord Message - Rebooting"
          community.general.discord:
            webhook_id: "{{ item.id }}"
            webhook_token: "{{ item.token }}"
            content: "Rebooting Host Machine: {{ inventory_hostname }}"
            username: "Ansible Alerts"
          loop:
            - { id: "{{ hl_homelab_server_alerts_id }}", token: "{{ hl_homelab_server_alerts_token }}" }

        - name: Reboot Server
          ansible.builtin.reboot:

        # --- Discord Messages ---
        - name: "Discord Message - Online"
          community.general.discord:
            webhook_id: "{{ item.id }}"
            webhook_token: "{{ item.token }}"
            content: "Host Machine Online: {{ inventory_hostname }}"
            username: "Ansible Alerts"
          loop:
            - { id: "{{ hl_homelab_server_alerts_id }}", token: "{{ hl_homelab_server_alerts_token }}" }

      # --------------- ERROR HANDLING --------------- #
      rescue:
        - name: "Discord Messages - Alert"
          community.general.discord:
            webhook_id: "{{ item.id }}"
            webhook_token: "{{ item.token }}"
            content: "An Error Has Been Encountered Rebooting: {{ inventory_hostname }}."
            username: "Ansible Alerts"
          loop:
            - { id: "{{ hl_homelab_server_alerts_id }}", token: "{{ hl_homelab_server_alerts_token }}" }